//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuiltInMemo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuiltInMemo()
        {
            this.MyMemos = new HashSet<MyMemo>();
        }
    
        public int MemoId { get; set; }
        public string MemoName { get; set; }
        public int HebrewTimeId { get; set; }
        public Nullable<int> DayInWeek { get; set; }
        public string HebrewDayStart { get; set; }
        public string HebrewMonthStart { get; set; }
        public string HebrewDayEnd { get; set; }
        public string HebrewMonthEnd { get; set; }
    
        public virtual TimeType TimeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyMemo> MyMemos { get; set; }
    }
}
